---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: soknadsveiviser
  namespace: {{namespace}}
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}:{{version}}
  team: skjemadigitalisering
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: soknadsveiviserproxy
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        {{#each externalHosts as |url|}}
          - host: {{url}}
        {{/each}}
  liveness:
    path: /soknader/internal/isAlive
    initialDelay: 10
  readiness:
    path: /soknader/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: DECORATOR_URL
      value: {{decoratorurl}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{skjemabygging-proxy-url}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{skjemabygging-proxy-client-id}}
  envFrom:
    - secret: soknadsveiviser
