---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: soknadsveiviser
  namespace: {{NAMESPACE}}
  labels:
    team: {{NAMESPACE}}
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each INGRESSES as |url|}}
     - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: soknadsveiviserproxy
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        {{#each EXTERNAL_HOSTS as |url|}}
          - host: {{url}}
        {{/each}}
  liveness:
    path: /soknader/internal/isAlive
    initialDelay: 10
  readiness:
    path: /soknader/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: DECORATOR_URL
      value: {{DECORATOR_URL}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{SKJEMABYGGING_PROXY_URL}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{SKJEMABYGGING_PROXY_CLIENT_ID}}
  envFrom:
    - secret: soknadsveiviser
