// tslint:disable:max-line-length
export default {
  nb: {
    "avslutning.advarsel": `Ukomplette søknader tar ofte lengre tid å behandle, det er mulig å ettersende men vi anbefaler å sende komplett.`,
    "avslutning.sidetittel": `Last ned søknadspapirene`,
    "avslutning.vedlegg": `Vedlegg:`,
    "avslutning.sprakvelger.kunettsprak": `Skjemaet finnes kun på`,
    "avslutning.sprakvelger.label": `Velg språk du vil ha skjemapapirene på:`,
    "avslutning.sprakvelger.de": `Tysk`,
    "avslutning.sprakvelger.en": `Engelsk`,
    "avslutning.sprakvelger.es": `Spansk`,
    "avslutning.sprakvelger.fr": `Fransk`,
    "avslutning.sprakvelger.nb": `Norsk bokmål`,
    "avslutning.sprakvelger.nn": `Norsk nynorsk`,
    "avslutning.sprakvelger.pl": `Polsk`,
    "avslutning.sprakvelger.se": `Nord-samisk`,
    "avslutning.steg.sjekkbokser.tittel": `Velg hvilke vedlegg du sender ved søknaden`,
    "avslutning.steg.sjekkbokser.beskrivelse": `Hvis du ikke har alle dokumentene som er listet opp nedenfor kan du ettersende disse senere. Vær oppmerksom på at dette kan føre til at søknaden din ikke vil bli behandlet før du har ettersendt alle dokumentene.`,
    "avslutning.steg.sjekkbokser.markering": `Fjern markeringen på de vedleggene du <u>ikke</u> sender nå:`,
    "avslutning.steg.lastned.tittel": `Last ned søknad og vedlegg`,
    "avslutning.steg.lastned.knapp.ready": `Last ned`,
    "avslutning.steg.lastned.knapp.loading": `Initierer`,
    "avslutning.steg.lastned.knapp.cover": `Henter filer`,
    "avslutning.steg.lastned.knapp.merge": `Slår sammen`,
    "avslutning.steg.lastned.knapp.download": `Laster ned`,
    "avslutning.steg.eksterne.tittel": `Disse dokumentene må du skaffe selv:`,
    "avslutning.steg.ettersendelse.tittel": `Disse dokumentene har du valgt å ettersende:`,
    "avslutning.steg.innsending.tittel": `Send det hele til NAV i posten`,
    "avslutning.steg.innsending.beskrivelse": `Adressen du sender søknaden til i NAV finner du på førstesidearket.`,
    "avslutning.steg.innsending.obs": `Viktig! Førstesiden må ligge øverst i søknaden din.`,
    "avslutning.steg.videre.tittel": `Hva skjer videre..`,
    "avslutning.steg.videre.beskrivelse": `Du hører fra oss så fort som vi har sett på søknaden din - Vi tar kontakt med deg om vi mangler noe.`,
    "personalia.bedrift.undertittel": `Oppgi hvem innsendelsen gjelder for`,
    "personalia.knapp": `Neste`,
    "personalia.sidetittel": `Din boligsituasjon`,
    "personalia.undertittel": `Min informasjon`,
    "personalia.error.fodselsnummer": `Du må fylle inn gyldig fødselsnummer eller D-nummer`,
    "personalia.error.name": `Navn er påkrevd`,
    "personalia.error.adresse": `Adresse er påkrevd`,
    "personalia.error.postnummer": `Postnummer er påkrevd`,
    "personalia.error.sted": `Du må fylle ut stedsnavn.`,
    "personalia.error.land": `Du må fylle ut land.`,
    "personalia.error.velgkontor": `Fyll inn hvilken enhet dokumentene skal sendes til`,
    "personalia.label.fodselsnummer": `Fødselsnummer`,
    "personalia.label.navn": `Navn`,
    "personalia.label.adresse": `Adresse`,
    "personalia.label.land": `Land`,
    "personalia.label.navkontor": `NAV-kontor`,
    "personalia.label.postnummer": `Postnummer`,
    "personalia.label.poststed": `Poststed`,
    "personalia.label.tidligereKontaktMedNAV": `Huk av her dersom du har vært i kontakt med NAV om denne saken tidligere`,
    "personalia.label.velgnavkontor": `Velg NAV-kontor`,
    "personalia.bedrift.flerepersoner": `Flere personer samtidig`,
    "personalia.bedrift.ikkeFodselsnummerDnummer": `Personen har ikke et fødselsnummer eller D-nummer`,
    "personalia.bedrift.oppgiFodselsnummerDnummer": `Personen har et fødselsnummer eller D-nummer`,
    "personalia.bedrift.tiltaksbedrift": `Tiltaksbedrifter, kursarrangører og andre virksomheter`,
    "personalia.ikkeFodselsnummerDnummer": `Jeg har ikke fødselsnummer`,
    "personalia.oppgiFodselsnummerDnummer": `Jeg har et fødselsnummer eller D-nummer`,
    "personalia.undertekstbold.adresse": `Hvis du har en adresse du bor på i Norge, bruk den adressen. Hvis du ikke har en adresse i Norge, vennligst fyll inn din vanlige adresse.`,
    "personalia.undertekstbold.flerepersoner": `Forklarende tekst for flere personer. Forklarende tekst for flere personer. Du må velge NAV-kontor som arkene skal sendes til.`,
    "personalia.undertekstbold.gdpr": `Denne informasjonen blir ikke lagret, og brukes kun for å generere en førsteside for innsending på papir.`,
    "personalia.undertekstbold.tiltaksbedrift": `Forklarende tekst for tiltaksbedrifter. Forklarende tekst for tiltaksbedrifter. Du må velge NAV-kontor som du har hatt kontakt med.`,
    "klage.knapp": `Klage på vedtak`,
    "klage.tittel.underbanner": `Klage på vedtak`,
    "klage.ettersende": `Skal du ettersende dokumentasjon til en tidligere innsendt klage?`,
    "ettersendelser.knapp": `Ettersendelse`,
    "ettersendelser.tittel.underbanner": `Velg hvilken dokumentasjon du skal ettersende`,
    "ettersendelser.mellomledd.digital.tittel": `Ettersende til elektronisk søknad`,
    "ettersendelser.mellomledd.digital.beskrivelse": `Her kan du ettersende dokumentasjon til en tidligere innsendt elektronisk søknad.`,
    "ettersendelser.mellomledd.digital.advarsel": `NB! Fristen for å ettersende dokumentasjon til en elektronisk søknad går ut etter 14 dager. Hvis fristen har gått ut må du ettersende dokumentasjonen på papir (se nedenfor).`,
    "ettersendelser.mellomledd.digital.knapp": `Ettersend digitalt`,
    "ettersendelser.mellomledd.papir.tittel": `Ettersende til en papirsøknad`,
    "ettersendelser.mellomledd.papir.beskrivelse": `Her kan du ettersende dokumentasjon til en tidligere innsendt papirsøknad, og til en elektronisk søknad dersom ettersendingsfristen har gått ut.`,
    "ettersendelser.mellomledd.papir.knapp": `Ettersend på papir`,
    "ettersendelser.mellomledd.klage.tittel": `Ettersende til klage / anke`,
    "ettersendelser.mellomledd.klage.beskrivelse": `Ettersend dokumentasjon til en tidligere innsendt klage eller anke. `,
    "ettersendelser.mellomledd.klage.knapp": `Ettersend til klage / anke`,
    "kategori.beskrivelse": `Skjemaer og søknader`,
    "kategori.velg": `Meny`,
    "kategorier.knapp.bedrift": `Bedrift`,
    "kategorier.knapp.engelsk": `English`,
    "kategorier.knapp.person": `Person`,
    "underkategori.tittel.alfabet": `A til Å`,
    "stegindikator.steg1": `Velg søknadstype`,
    "stegindikator.steg2": `Velg vedlegg`,
    "stegindikator.steg3": `Velg ettersendelser`,
    "stegindikator.steg4": `Din boligsituasjon`,
    "stegindikator.steg5": `Last ned og send`,
    "velgvedlegg.informasjonspanel.ingress": `Det viktig at du svarer på alle spørsmålene nedenfor. `,
    "velgvedlegg.informasjonspanel.beskrivelse": `Svarene dine vil avgjøre hvilke vedlegg du må legge ved søknaden. `,
    "velgvedlegg.informasjonspanel.lenke": ``,
    "velgvedlegg.informasjonspanel.tittel": `Hva skal du sende med søknaden?`,
    "velgvedlegg.beskrivelse": `Huk av det som gjelder for deg`,
    "velgvedlegg.checkbokspanel": `Velg det som gjelder for deg`,
    "velgvedlegg.innholdstittel": `Valg av vedlegg`,
    "velgvedlegg.knapp": `Neste`,
    "velgvedlegg.sidetittel": `Velg dokumentasjon`,
    "velgvedlegg.lesmer.apne": `Les mer`,
    "velgvedlegg.lesmer.lukk": `Lukk`,
    "velgvedlegg.ja": "Ja",
    "velgvedlegg.nei": "Nei",
    "velgvedlegg.vedlegg": "Vedlegg: ",
    "dinevedlegg.tittel": `Dine vedlegg`,
    "dinevedlegg.pakrevd": `Påkrevd vedlegg: `,
    "dinevedlegg.ingress": `På bakgrunn av svarene dine må du legge ved følgende vedlegg: `,
    "dinevedlegg.beskrivelse": `Du kan laste ned søknadsskjema og vedleggsskjema på neste side. Send kopi av dokumentasjonen og behold originalen selv (med unntak av kvitteringer). Kvitteringer må være originaler.`,
    "vissoknadsobjekter.bannertittel": `Søknad om`,
    "vissoknadsobjekter.papirsoknader": `Papirsøknader`,
    "vissoknadsobjekter.papirsoknader.beskrivelse": `Søknadene nedenfor bruker du når du ikke har elektronisk ID. Vær oppmerksom på at en søknad på papir tar lenger tid på grunn av postgang og manuell håndtering av søknadspapirene.`,
    "vissoknadsobjekter.ekspanderbartpanel.tittel": `Jeg har ikke elektronisk ID`,
    "vissoknadsobjekter.innholdstittel": `Hva ønsker du å søke om?`,
    "vissoknadsobjekter.relevantinformasjon": `Relatert informasjon`,
    "vissoknadsobjekter.knapp.soknadpapapir": `Søk på papir`,
    "vissoknadsobjekter.knapp.soknadsdialog": `Søk digitalt`,
    "vissoknadsobjekter.knapp.dokumentinnsending": `Søk digitalt`,
    "vissoknadsobjekter.tittel": `Jeg vil søke om`,
    "vissoknadsobjekter.ikkeelektroniskID": `Jeg har ikke elektronisk ID`,
    "feil.tekst.ingen": "Feil, fant ikke tekst.",
    "feil.tekst.udefinert": "Udefinert tekst på objektet",
    "veileder.ettersendelse.tittel": "Ettersend dokumentasjon",
    "veileder.ettersendelse.steg1": `1. Velg hvilken søknad du vil ettersende til i oversikten nedenfor.`,
    "veileder.ettersendelse.steg2": `2. Klikk på knappen «Ettersendelse» på den søknaden det gjelder og følg instruksjonene videre.`,
    "veileder.klage.tittel": "Klage på vedtak",
    "veileder.klage.steg1": `1. Velg hvilken søknad klagen gjelder i oversikten nedenfor. `,
    "veileder.klage.steg2": `2. Klikk på knappen «Klage / anke» på den søknaden det gjelder og følge instruksjonene videre.`,
    "errors.api.fetch": "Oisann, noe gikk galt ved henting av data!",
    "errors.api.kategori": `Vi fant dessverre ikke valgt kategori.`,
    "errors.api.underkategori": `Vi fant dessverre ikke valgt underkategori.`,
    "errors.api.soknader": `Vi fant ingen søknader under denne kategorien.`,
    "errors.api.soknadsobjekt": `Vi fant dessverre ikke den valgte søknaden.`,
    "notFound.tittel": "OOPS, NOE GIKK GALT",
    "notFound.beskrivelse": `Koblingen du klikket kan være ødelagt, eller siden kan ha blitt fjernet.`,
    "notFound.goto.nav": `Gå til nav.no`,
    "notFound.goto.soknadsveiviser": `Gå til skjemaer og søknader`
  },
  en: {
    "avslutning.advarsel": `Incomplete applications will take longer time to process. It is possible to send documents in later, however, it is recommended to send the application complete with all documents from the start.`,
    "avslutning.sidetittel": `Download the application papers`,
    "avslutning.vedlegg": `Attachment:`,
    "avslutning.sprakvelger.kunettsprak": `The form only exists in`,
    "avslutning.sprakvelger.label": `Choose the language you want for the PDFs:`,
    "avslutning.sprakvelger.de": `German`,
    "avslutning.sprakvelger.en": `English`,
    "avslutning.sprakvelger.es": `Spanish`,
    "avslutning.sprakvelger.fr": `French`,
    "avslutning.sprakvelger.nb": `Norwegian (bokmål)`,
    "avslutning.sprakvelger.nn": `Norwegian (nynorsk)`,
    "avslutning.sprakvelger.pl": `Polish`,
    "avslutning.sprakvelger.se": `Northern sami`,
    "avslutning.steg.sjekkbokser.tittel": `Select the attachments you are able to send at this time`,
    "avslutning.steg.sjekkbokser.beskrivelse": `If you do not have all the documents listed below you can forward these later. Please note that this may result in your application not being processed until all documents are submitted.`,
    "avslutning.steg.sjekkbokser.markering": `Uncheck any attachments you are unable to send at this time:`,
    "avslutning.steg.lastned.tittel": `Download the application and attachments"`,
    "avslutning.steg.lastned.knapp.ready": `Download`,
    "avslutning.steg.lastned.knapp.loading": `Initiating`,
    "avslutning.steg.lastned.knapp.cover": `Retrieving files`,
    "avslutning.steg.lastned.knapp.merge": `Merging files`,
    "avslutning.steg.lastned.knapp.download": `Downloading`,
    "avslutning.steg.eksterne.tittel": `You must obtain these documents yourself:`,
    "avslutning.ettersendelse.tittel": `You have stated that these documents will be submitted later:`,
    "avslutning.steg.innsending.tittel": `Send all documents to NAV by post`,
    "avslutning.steg.innsending.beskrivelse": `The application is to be sent to NAV to the address on the first page.`,
    "avslutning.steg.innsending.obs": `Important! The first page must be at the top of your application.`,
    "avslutning.steg.videre.tittel": `What happens next..`,
    "avslutning.steg.videre.beskrivelse": `You will hear from oss as soon as we have processed your application. We will be in touch if we are missing some documents.`,
    "personalia.bedrift.undertittel": `State who the submission is for`,
    "personalia.knapp": `Next`,
    "personalia.sidetittel": `Living situation`,
    "personalia.undertittel": `My information`,
    "personalia.error.fodselsnummer": `You need to fill in a valid Norwegian national identification number`,
    "personalia.error.name": `Name is required`,
    "personalia.error.adresse": `Address is required`,
    "personalia.error.postnummer": `Postal code is required`,
    "personalia.error.sted": `City is required`,
    "personalia.error.land": `Country is required`,
    "personalia.error.velgkontor": `Please select which NAV-unit the documents shall be sent to`,
    "personalia.label.fodselsnummer": `Norwegian national identification number`,
    "personalia.label.navn": `Name`,
    "personalia.label.adresse": `Address`,
    "personalia.label.land": `Country`,
    "personalia.label.navkontor": `NAV unit`,
    "personalia.label.postnummer": `Postal code`,
    "personalia.label.poststed": `City`,
    "personalia.label.tidligereKontaktMedNAV": `Check if you have been in contact with NAV about this matter earlier`,
    "personalia.label.velgnavkontor": `Choose NAV unit`,
    "personalia.bedrift.flerepersoner": `Multiple people`,
    "personalia.bedrift.ikkeFodselsnummerDnummer": `The person does not have a Norwegian national identification number`,
    "personalia.bedrift.oppgiFodselsnummerDnummer": `The person has a Norwegian national identification number`,
    "personalia.bedrift.tiltaksbedrift": `Tiltaksbedrifter, kursarrangører og andre virksomheter`,
    "personalia.ikkeFodselsnummerDnummer": `I do not have a Norwegian national identification number`,
    "personalia.oppgiFodselsnummerDnummer": `I have a Norwegian national identification number`,
    "personalia.undertekstbold.adresse": `If you have an address you stay at in Norway, use that address. Otherwise, please fill inn your the address you currently reside in.`,
    "personalia.undertekstbold.flerepersoner": `Forklarende tekst for flere personer. Forklarende tekst for flere personer. Du må velge NAV-kontor som arkene skal sendes til.`,
    "personalia.undertekstbold.gdpr": `This information is not stored, and is only used to generate a front page for your application.`,
    "personalia.undertekstbold.tiltaksbedrift": `Forklarende tekst for tiltaksbedrifter. Forklarende tekst for tiltaksbedrifter. Du må velge NAV-kontor som du har hatt kontakt med.`,
    "klage.knapp": `Appeal`,
    "klage.tittel.underbanner": `Appeal`,
    "klage.ettersende": `Are you going to submit documentation to a previously filed complaint?`,
    "ettersendelser.knapp": `Forward`,
    "ettersendelser.tittel.underbanner": `Choose attachments to forward`,
    "ettersendelser.mellomledd.tittel": `Forward documentation`,
    "ettersendelser.mellomledd.undertittel": `Application`,
    "ettersendelser.mellomledd.digital.tittel": `Forward to electronic application`,
    "ettersendelser.mellomledd.digital.beskrivelse": `Here you can forward documentation to a previously submitted electronic application.`,
    "ettersendelser.mellomledd.digital.advarsel": `NB! The deadline for forwarding documentation to an electronic application expires after 14 days. If the deadline has expired, you will need to submit the documentation on paper (see below).`,
    "ettersendelser.mellomledd.digital.knapp": `Forward digitally`,
    "ettersendelser.mellomledd.papir.tittel": `Forward on paper`,
    "ettersendelser.mellomledd.papir.beskrivelse": `Here you can forward documentation to a previously submitted paper application, and to an electronic application if the forward deadline has expired.`,
    "ettersendelser.mellomledd.papir.knapp": `Forward on paper`,
    "ettersendelser.mellomledd.klage.tittel": `Forward to complaint / appeal`,
    "ettersendelser.mellomledd.klage.beskrivelse": `Forwarding documentation to a previously filed complaint or appeal.`,
    "ettersendelser.mellomledd.klage.knapp": `Forward to complaint / appeal`,
    "kategori.beskrivelse": `Forms and applications`,
    "kategori.velg": `Menu`,
    "kategorier.knapp.bedrift": `Employers`,
    "kategorier.knapp.engelsk": `English`,
    "kategorier.knapp.person": `Person`,
    "underkategori.tittel.alfabet": `A to Z`,
    "stegindikator.steg1": `Type of application`,
    "stegindikator.steg2": `Choose documentation`,
    "stegindikator.steg3": `Later submittion`,
    "stegindikator.steg4": `Living situation`,
    "stegindikator.steg5": `Download and send`,
    "velgvedlegg.informasjonspanel.ingress": `It is important that you answer the questions below.`,
    "velgvedlegg.informasjonspanel.beskrivelse": `Your situation determines which documentation you must submit with the application for it to be processed by NAV.`,
    "velgvedlegg.informasjonspanel.lenke": ``,
    "velgvedlegg.informasjonspanel.tittel": `What should you submit with your application?`,
    "velgvedlegg.beskrivelse": `Check off the statements that applies to you`,
    "velgvedlegg.checkbokspanel": `Check the boxes that describe your situation`,
    "velgvedlegg.innholdstittel": `Attachment choice`,
    "velgvedlegg.knapp": `Next`,
    "velgvedlegg.sidetittel": `Select documentation`,
    "velgvedlegg.lesmer.apne": `Learn more`,
    "velgvedlegg.lesmer.lukk": `Close`,
    "velgvedlegg.ja": "Yes",
    "velgvedlegg.nei": "No",
    "velgvedlegg.vedlegg": "Attachment: ",
    "dinevedlegg.tittel": `Your attachments`,
    "dinevedlegg.pakrevd": `Required attachment: `,
    "dinevedlegg.ingress": `Based on your answers, you must submit the following attachments: `,
    "dinevedlegg.beskrivelse": `You can download the application form and attachments on the next page. Send a copy of the documentation and keep the original yourself (with the exception of receipts). Receipts must be originals.`,
    "vissoknadsobjekter.bannertittel": `Application for`,
    "vissoknadsobjekter.papirsoknader": `Applications by mail`,
    "vissoknadsobjekter.papirsoknader.beskrivelse": `The applications below are used when you do not have an electronic ID. Please note that an application by paper takes longer time to process due to mailing and manual handling of the application papers.`,
    "vissoknadsobjekter.ekspanderbartpanel.tittel": `I do not have a digital ID`,
    "vissoknadsobjekter.innholdstittel": `What do you want to apply for?`,
    "vissoknadsobjekter.relevantinformasjon": `Relatert information`,
    "vissoknadsobjekter.knapp.soknadpapapir": `Apply on paper`,
    "vissoknadsobjekter.knapp.soknadsdialog": `Apply digitally`,
    "vissoknadsobjekter.knapp.dokumentinnsending": `Apply digitally`,
    "vissoknadsobjekter.tittel": `I want to apply for`,
    "vissoknadsobjekter.ikkeelektroniskID": `I do not have an electronic ID`,
    "feil.ingentekst": "Error, did not find text.",
    "veileder.ettersendelse.tittel": "Forward additional documentation",
    "veileder.ettersendelse.steg1": `1. To submit additional documentation for a previously submitted application, you must find the relevant application in the overview below. `,
    "veileder.ettersendelse.steg2": `2. Click the «Forward»-button beside the correct application, and follow the instructions from there.`,
    "veileder.klage.tittel": "Complaint and appeal (Norwegian only)",
    "veileder.klage.steg1": `1. To submit a complaint regarding a decision NAV has made in your case, you have to find the relevant application in the overview below.`,
    "veileder.klage.steg2": `2. Click the «Complaint»-button beside the correct application, and follow further instructions. `,
    "errors.api.fetch": "Ops, something went wrong while fetching data!",
    "errors.api.kategori": `We did not find the chosen category.`,
    "errors.api.underkategori": `We did not find the chosen subcategory.`,
    "errors.api.soknader": `We did not find any applications under this category.`,
    "errors.api.soknadsobjekt": `We did not find the chosen application.`,
    "notFound.tittel": "Ops, something went wrong",
    "notFound.beskrivelse": `The link you clicked may be broken or the page may have been removed.`,
    "notFound.goto.nav": `Go to nav.no`,
    "notFound.goto.soknadsveiviser": `Go to forms and applications`
  }
};
