export default {
  "tittel.soknader": "Søknader",
  "avslutning.advarsel": `Ukomplette søknader tar ofte lengre tid å behandle. Det er mulig å ettersende men vi anbefaler å sende komplett.`,
  "avslutning.sidetittel": `Last ned søknadspapirene`,
  "avslutning.vedlegg": `Vedlegg:`,
  "avslutning.sprakvelger.kunettsprak": `Skjemaet finnes kun på`,
  "avslutning.sprakvelger.label": `Velg språk du vil ha søknadspapirene på:`,
  "avslutning.sprakvelger.de": `Tysk`,
  "avslutning.sprakvelger.en": `Engelsk`,
  "avslutning.sprakvelger.es": `Spansk`,
  "avslutning.sprakvelger.fr": `Fransk`,
  "avslutning.sprakvelger.nb": `Norsk bokmål`,
  "avslutning.sprakvelger.nn": `Norsk nynorsk`,
  "avslutning.sprakvelger.pl": `Polsk`,
  "avslutning.sprakvelger.se": `Nord-samisk`,
  "avslutning.steg.sjekkbokser.tittel": `Velg hvilke vedlegg du sender ved søknaden`,
  "avslutning.steg.sjekkbokser.beskrivelse": `Hvis du ikke har alle dokumentene som er listet opp nedenfor kan du ettersende disse senere. Det kan føre til at søknaden din ikke vil bli behandlet før du har ettersendt alle dokumentene.`,
  "avslutning.steg.sjekkbokser.markering": `Fjern markeringen på de vedleggene du <u>ikke</u> sender nå:`,
  "avslutning.steg.lastned.tittel": `Last ned søknad og vedlegg`,
  "avslutning.steg.lastned.knapp.ready": `Last ned`,
  "avslutning.steg.lastned.knapp.loading": `Initierer`,
  "avslutning.steg.lastned.knapp.cover": `Henter filer`,
  "avslutning.steg.lastned.knapp.merge": `Slår sammen`,
  "avslutning.steg.lastned.knapp.download": `Laster ned`,
  "avslutning.steg.forsteside.tittel": `Last ned "Førsteside til saken din"`,
  "avslutning.steg.forsteside.pdf.tittel": `Førsteside`,
  "avslutning.steg.forsteside.beskrivelse": `Dette førstesidearket inneholder viktig informasjon om hvilken <b>enhet</b> i NAV som skal motta dokumentasjonen. Den inneholder også adressen du skal sende dokumentene til.`,
  "avslutning.steg.forsteside.nedlastingsfeil": `Noe gikk feil. Prøv igjen senere. Vi arbeider med å rette feilen.`,
  "avslutning.steg.forsteside.nedlastingsfeil.hotjartrigger": `Hjelp oss å forstå hva feilen er.`,
  "avslutning.steg.nedlasting.skjema.tittel": `Last ned skjema {skjemanummer}`,
  "avslutning.steg.nedlasting.skjema.beskrivelse": `Søknaden må fylles ut og undertegnes.`,
  "avslutning.steg.nedlasting.skjema.obs":
    'Det er viktig at du bruker Adobe Acrobat Reader når du skal fylle ut skjemaet. <br /> <a href="https://get.adobe.com/no/reader/" target="_blank" rel="noopener noreferrer" class="lenke">Last ned Adobe Acrobat Reader</a> (lenke åpner i et nytt vindu).',
  "avslutning.steg.nedlasting.vedlegg.tittel": `Last ned vedleggsskjema`,
  "avslutning.steg.nedlasting.vedlegg.beskrivelse": `Vedleggsskjema(ene) må fylles ut og undertegnes.`,
  "avslutning.steg.eksterne.tittel": `Disse dokumentene må du skaffe selv:`,
  "avslutning.steg.ettersendelse.tittel": `Disse dokumentene har du valgt å ettersende:`,
  "avslutning.steg.innsending.tittel": `Send det hele til NAV i posten`,
  "avslutning.steg.innsending.beskrivelse": `Adressen du sender dokumentene til i NAV finner du på førstesidearket.`,
  "avslutning.steg.innsending.obs": `Førstesiden må ligge øverst i dokumentene.`,
  "avslutning.steg.videre.tittel": `Hva skjer videre?`,
  "avslutning.steg.videre.beskrivelse": `Du hører fra oss så fort som vi har sett på saken din. Vi tar kontakt med deg om vi mangler noe.`,
  "personalia.bedrift.undertittel": `Oppgi hvem innsendelsen gjelder for`,
  "personalia.knapp": `Neste`,
  "personalia.velgenhet": `Velg enhet`,
  "personalia.sidetittel": `Din boligsituasjon`,
  "personalia.undertittel": `Oppgi hvem innsendelsen gjelder for`,
  "personalia.error.fodselsnummer": `Du må fylle inn gyldig fødselsnummer eller D-nummer`,
  "personalia.error.name": `Navn er påkrevd`,
  "personalia.error.adresse": `Adresse er påkrevd`,
  "personalia.error.postnummer": `Postnummer er påkrevd`,
  "personalia.error.sted": `Du må fylle ut stedsnavn.`,
  "personalia.error.land": `Du må fylle ut land.`,
  "personalia.error.velgkontor": `Velg hvilken enhet dokumentene skal sendes til`,
  "personalia.error.enhet": `Velg en gyldig enhet`,
  "personalia.error.velgsituasjon": `Du må velge én av situasjonene under`,
  "personalia.label.fodselsnummer": `Fødselsnummer`,
  "personalia.label.navn": `Navn`,
  "personalia.label.adresse": `Adresse`,
  "personalia.label.land": `Land`,
  "personalia.label.navkontor": `NAV-enhet`,
  "personalia.label.postnummer": `Postnummer`,
  "personalia.label.poststed": `Poststed`,
  "personalia.label.tidligereKontaktMedNAV": `Huk av her dersom du har vært i kontakt med NAV om denne saken tidligere`,
  "personalia.label.velgnavkontor": `Velg NAV-enhet`,
  "personalia.bedrift.flerepersoner": `Flere personer samtidig`,
  "personalia.bedrift.ikkeFodselsnummerDnummer": `Én person som ikke har fødselsnummer eller D-nummer`,
  "personalia.bedrift.oppgiFodselsnummerDnummer": `Én person som har fødselsnummer eller D-nummer`,
  "personalia.bedrift.tiltaksbedrift": `Tiltaksbedrifter, kursarrangører og andre virksomheter`,
  "personalia.ikkeFodselsnummerDnummer": `Jeg har ikke fødselsnummer`,
  "personalia.oppgiFodselsnummerDnummer": `Jeg har et fødselsnummer eller D-nummer`,
  "personalia.undertekstbold.adresse": `Hvis du har en adresse du bor på i Norge, bruk den adressen. Hvis du ikke har en adresse i Norge, vennligst fyll inn din vanlige adresse.`,
  "personalia.undertekstbold.flerepersoner": `OBS: Hvis du skal permittere arbeidstakere som bor i flere fylker skal du sende skjemaet til det fylket der de fleste bor. Dette valget skal ikke brukes for yrkesskademeldinger, sykepenger og arbeidsrettede tiltak.

For at papirene dine skal komme raskt fram til riktig sted i NAV, skriver du inn hvilken enhet som skal behandle saken din. Vet du at personene tilhører ulike NAV-kontor, gjentar du prosedyren for hvert kontor du sender til. Er du i tvil, kan du kontakte NAV på telefon 55 55 33 36.`,
  "personalia.undertekstbold.gdpr": `Denne informasjonen brukes for å generere en førsteside for innsending på papir.`,
  "personalia.undertekstbold.tiltaksbedrift": `Eksempel: Søknader, faktura, deltakerliste, eller annet som gjelder arbeidsrettede tiltak

For at papirene dine skal komme raskt fram til riktig sted i NAV, skriver du inn hvilken enhet som skal behandle saken din. Vet du at personene tilhører ulike NAV-kontor, gjentar du prosedyren for hvert kontor du sender til. Er du i tvil, kan du kontakte NAV på telefon 55 55 33 36.`,
  "klageanke.knapp": `Klage eller anke`,
  "klage.tittel.underbanner": `Klage på vedtak`,
  "klage.ettersendelse.tittel.underbanner": `Ettersende til klage på vedtak`,
  "klage.videresendt.enhet": `Har du fått brev om at klagen din er videresendt til NAV Klageinstans?`,
  "klage.velg.behandlende.enhet": `Velg enhet som behandler klagen din (se i brevet du har fått)`,
  "klage.mellomledd.tittel": `Klage på vedtak`,
  "klage.mellomledd.knapp": `Klage`,
  "klage.mellomledd.beskrivelse": `Her kan du klage på vedtak fra NAV`,
  "klage.ettersende": `Skal du ettersende dokumentasjon til en tidligere innsendt klage?`,
  "anke.tittel.underbanner": `Anke`,
  "anke.ettersendelse.tittel.underbanner": `Ettersende til anke`,
  "anke.mellomledd.tittel": `Anke`,
  "anke.mellomledd.knapp": `Anke`,
  "anke.mellomledd.beskrivelse": `Her kan du anke til Trygderetten hvis du ikke fikk medhold i klagen `,
  "anke.ettersende": `Skal du ettersende dokumentasjon til en tidligere innsendt anke?`,
  "anke.eller.klage.sidetittel": `Velg mellom klage eller anke`,
  "anke.eller.klage.meta_desc": `{soknadsnavn}: Klage eller anke`,
  "ettersendelser.knapp": `Ettersendelse`,
  "ettersendelser.tittel.underbanner": `Velg hvilken dokumentasjon du skal ettersende`,
  "ettersendelser.mellomledd.tittel": `Velg ettersendelse`,
  "ettersendelser.mellomledd.soknad.tittel": `Ettersende til en søknad`,
  "ettersendelser.mellomledd.soknad.beskrivelse": `Her kan du ettersende dokumentasjon til en tidligere innsendt søknad.`,
  "ettersendelser.mellomledd.soknad.meta_desc": `Ettersendelse av dokumentasjon til en søknad om {soknadsnavn}.`,
  "ettersendelser.mellomledd.soknad.knapp": `Ettersend på papir`,
  "ettersendelser.mellomledd.digital.knapp": `Ettersend digitalt`,
  "ettersendelser.mellomledd.klage.knapp": `Ettersend til klage`,
  "ettersendelser.mellomledd.klage.beskrivelse": `Velg ‘Ettersend til klage’ hvis du har klagd på et vedtak og ønsker å sende tilleggsdokumentasjon.`,
  "ettersendelser.mellomledd.anke.knapp": `Ettersend til anke`,
  "ettersendelser.mellomledd.anke.beskrivelse": `Velg ‘Ettersend til anke’ hvis du har anket til Trygderetten og ønsker å sende tilleggsdokumentasjon.`,
  "ettersendelser.mellomledd.klageanke.tittel": `Ettersende til klage eller anke`,
  sidetittel: `Søknad og skjema`,
  sideingress: `Du finner søknader og skjemaer, mulighet for ettersendelse av dokumentasjon og klageskjema når du velger emne nedenfor.`,
  "kategori.velg": `Søknadskategorier`,
  "kategori.meta_desc": `{kategoritittel}: Send inn søknad / skjema, tilleggsdokumentasjon  eller klage-/ankeskjema.`,
  "kategorier.knapp.bedrift": `Bedrift`,
  "kategorier.knapp.engelsk": `English`,
  "kategorier.knapp.person": `Person`,
  "underkategori.meta_desc": `{underkategorinavn}: {utlisting}`,
  "stegindikator.steg1": `Velg søknadstype`,
  "stegindikator.steg2": `Velg vedlegg`,
  "stegindikator.steg3": `Velg ettersendelser`,
  "stegindikator.steg4": `Din boligsituasjon`,
  "stegindikator.steg5": `Last ned og send`,
  "velgvedlegg.informasjonspanel.ingress.bedrift": `Når du sender inn en sak til NAV kan vi trenge ekstra dokumentasjon avhengig av situasjonen.`,
  "velgvedlegg.informasjonspanel.ingress.person": `Når du sender inn en søknad til NAV kan vi trenge ekstra dokumentasjon basert på din livssituasjon.`,
  "velgvedlegg.informasjonspanel.sporsmal": `Trenger du hjelp til å velge dokumentasjon?`,
  "velgvedlegg.informasjonspanel.tittel": `Dokumentasjon`,
  "velgvedlegg.beskrivelse": `Huk av det som gjelder for deg`,
  "velgvedlegg.checkbokspanel": `Velg det som gjelder for deg`,
  "velgvedlegg.innholdstittel": `Valg av vedlegg`,
  "velgvedlegg.knapp": `Neste`,
  "velgvedlegg.sidetittel": `Velg dokumentasjon`,
  "velgvedlegg.lesmer.hvaerdette": `Les mer`,
  "velgvedlegg.lesmer.apne": `Les mer om dette vedlegget`,
  "velgvedlegg.lesmer.lukk": `Lukk`,
  "velgvedlegg.ja": "Ja",
  "velgvedlegg.nei": "Nei",
  "velgvedlegg.vedlegg": "Vedlegg: ",
  "dinevedlegg.tittel": `Dette må du legge ved søknaden`,
  "dinevedlegg.pakrevd": `Påkrevd vedlegg: </br>`,
  "dinevedlegg.sender.na": `Jeg sender dette nå`,
  "dinevedlegg.sender.senere": `Jeg sender dette senere`,
  "dinevedlegg.ingress.pakrevde": `Disse dokumentene trenger vi for å behandle saken din, uavhengig av din situasjon:`,
  "dinevedlegg.ingress.situasjonsbestemte": `Ut fra det du har svart på spørsmålene må du sende inn denne dokumentasjonen:`,
  "dinevedlegg.beskrivelse": `Du kan laste ned søknadsskjema og vedleggsskjema på neste side. Send kopi av dokumentasjonen og behold originalen selv. Kvitteringer må være originaler.`,
  "vissoknadsobjekter.papirsoknader": `Papirsøknader`,
  "vissoknadsobjekter.papirsoknader.beskrivelse": `Søknadene nedenfor bruker du når du ikke har elektronisk ID. Vær oppmerksom på at en søknad på papir tar lenger tid på grunn av postgang og manuell håndtering av søknadspapirene.`,
  "vissoknadsobjekter.ekspanderbartpanel.tittel": `Send søknad på papir`,
  "vissoknadsobjekter.innholdstittel": `Hva ønsker du å søke om?`,
  "vissoknadsobjekter.relevantinformasjon": `Relatert informasjon`,
  "vissoknadsobjekter.knapp.soknadpapapir": `Send på papir`,
  "vissoknadsobjekter.knapp.soknadsdialog": `Send digitalt`,
  "vissoknadsobjekter.knapp.fyllut": `Søk her`,
  "vissoknadsobjekter.knapp.dokumentinnsending": `Send digitalt`,
  "vissoknadsobjekter.tittel": `Digital søknad om`,
  "vissoknadsobjekter.ikkeelektroniskID": `Send på papir`,
  "feil.tekst.ingen": "Feil, fant ikke tekst.",
  "feil.tekst.udefinert": "Udefinert tekst på objektet",
  "veileder.ettersendelse.tittel": "Ettersend dokumentasjon",
  "veileder.ettersendelse.steg1": `1. Velg hvilken søknad du vil ettersende til i oversikten nedenfor.`,
  "veileder.ettersendelse.steg2": `2. Klikk på knappen «Ettersendelse» på den søknaden det gjelder og følg instruksjonene videre.`,
  "veileder.klage.tittel": "Klage på vedtak",
  "veileder.klage.steg1": `1. Velg hvilken søknad klagen gjelder i oversikten nedenfor. `,
  "veileder.klage.steg2": `2. Klikk på knappen «Klage eller anke» på den søknaden det gjelder og følg instruksjonene videre.`,
  "errors.api.fetch": "Oisann, noe gikk galt ved henting av data!",
  "errors.api.kategori": `Vi fant dessverre ikke valgt kategori.`,
  "errors.api.underkategori": `Vi fant dessverre ikke valgt underkategori.`,
  "errors.api.soknader": `Vi fant ingen søknader under denne kategorien.`,
  "errors.api.soknadsobjekt": `Vi fant dessverre ikke den valgte søknaden.`,
  "notFound.tittel": "OOPS, NOE GIKK GALT",
  "notFound.beskrivelse": `Koblingen du klikket kan være ødelagt, eller siden kan ha blitt fjernet.`,
  "notFound.goto.nav": `Gå til nav.no`,
  "notFound.goto.soknadsveiviser": `Gå til skjemaer og søknader`,
  "skjemalenke.lastned": `Last ned skjema:`,
  "skjemautlisting.vedleggsskjema": `Vedleggsskjema:`,
  "skjemautlisting.tilveiviser": `Til veiviseren:`,
  "skjemautlisting.lenketil.sed": `SED-skjemaer`,
  "skjemautlisting.lenketil.skjema": `Alle skjemaer`,
  "skjemautlisting.lenketil.detaljert": `Søknader og skjemaer listet ut etter visning`,
  "skjemautlisting.detaljert.forklaring": `Bruk denne lista hvis du raskt vil finne ut hvor et skjema er publisert. Søknader som ikke har skjemaer vises bare i denne lista.`,
  "skjemautlisting.sed.forklaring": `<p>Denne siden inneholder en oversikt over de SED (Strukturerte Elektroniske Dokumenter) som skal benyttes i utveksling av trygdeopplysninger med EU/EØS-land i henhold til forordning 883/2004 og 987/2009. SED kan kun sendes til kompetente institusjoner i det enkelte EU/EØS-land. De kompetente institusjonene finnes i EUs <a class="lenke" href="https://ec.europa.eu/employment_social/social-security-directory/welcome?langId=no">institusjonskatalog</a>.</p>

<p>For hver SED finnes det også forklaringer i et eget dokument med samme nummer som skjemaet etterfulgt av - (bindestrek).</p>

<p>Innledningsvis under hvert fagområde er det en oversikt over alle flyter (og SED) som kan benyttes og en korrelasjonstabell som viser sammenhengen mellom tidligere E-skjemaer og de nye SED.</p>`,
  skjemautlisting: `Skjemautlisting`,
  "skjemautlisting.tabell.alleskjemaer": `Alle skjemaer`,
  "skjemautlisting.tabell.alle": `Alle`,
  "skjemautlisting.tabell.velgskjemaerfor": `Velg skjemaer for:`,
  "skjemautlisting.tabell.alleomrader": `Alle områder`,
  "skjemautlisting.tabell.soketterskjema": `Søk etter skjema:`,
  "skjemautlisting.tabell.skjemautenemneord": `Skjemaer uten emneord`,
  "skjemautlisting.tabell.skjemanummer": `ID`,
  "skjemautlisting.tabell.skjemanavn": `Skjemanavn`,
  "skjemautlisting.tabell.malgruppe": `Målgruppe`,
  "skjemautlisting.tabell.pdf": `Filer`,
  "vedleggsvalg.toggle.veiledning": `Ja`,
  "vedleggsvalg.toggle.ikkeveiledning": `Nei`,
  "vedleggsvalg.toggle.info.ja": `Når du har svart på spørsmålene under, får du en liste med dokumentasjon du må legge ved.`,
  "vedleggsvalg.toggle.info.nei": `Kryss av for hvilken dokumentasjon du sender inn.`,
  "sjekkbokser.pakrevde": `Påkrevde vedlegg`,
  "sjekkbokser.situasjonsbestemte": `Situasjonsbestemte vedlegg`,
};
