name: Build and deploy
on:
  pull_request:
    branches: [ master ]
  push:
env:
  CI: "true"
  IMAGE_REGISTRY: docker.pkg.github.com/${{ github.repository }}
  IMAGE_VERSION: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: soknadsveiviser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '18.12.1'
            cache: 'npm'
            cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Docker build and push
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
        run: |
          echo $GITHUB_TOKEN | docker login $IMAGE_REGISTRY -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --pull -t $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_REGISTRY/$IMAGE_NAME:latest .
          docker push $IMAGE_REGISTRY/$IMAGE_NAME --all-tags

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          namespace: skjemadigitalisering
          externalHosts:
            - dekoratoren.ekstern.dev.nav.no
            - skjemabygging-proxy.dev-fss-pub.nais.io
          ingresses:
            - https://www.intern.dev.nav.no/soknader
            - https://soknadsveiviser.ekstern.dev.nav.no/soknader
            - https://soknadsveiviser.intern.dev.nav.no/soknader
            - https://soknadsveiviser-q0.intern.dev.nav.no/soknader
            - https://soknadsveiviser-q1.intern.dev.nav.no/soknader
          image: $IMAGE_REGISTRY/$IMAGE_NAME
          version: $IMAGE_VERSION
          decoratorurl: https://dekoratoren.ekstern.dev.nav.no/
          skjemabygging-proxy-url: https://skjemabygging-proxy.dev-fss-pub.nais.io
          skjemabygging-proxy-client-id: 95170319-b4d7-4190-8271-118ed19bafbf
          EOF
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/vars.yaml

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          namespace: skjemadigitalisering
          externalHosts:
            - www.nav.no
            - skjemabygging-proxy.prod-fss-pub.nais.io
          ingresses:
            - https://www.nav.no/soknader
            - https://soknadsveiviser.intern.nav.no/soknader
          image: $IMAGE_REGISTRY/$IMAGE_NAME
          version: $IMAGE_VERSION
          decoratorurl: https://www.nav.no/dekoratoren/
          skjemabygging-proxy-url: https://skjemabygging-proxy.prod-fss-pub.nais.io
          skjemabygging-proxy-client-id: 031863f2-9881-44af-ace5-6b5ab52afeb1
          EOF
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/vars.yaml

  smoke-test-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Smoke test the deployed app
        env:
          CYPRESS_BASE_URL: https://www.nav.no/soknader
        run: npm run cypress:ci
