name: Manually triggered deployment
run-name: Manual deploy to ${{ inputs.environment }} [${{ github.ref_name }}]
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "preprod"
        type: choice
        options:
          - none
          - preprod
          - prod

jobs:
  build-and-push:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: skjemadigitalisering
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ github.event.inputs.environment }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-preprod:
    name: Deploy to preprod
    if: github.event.inputs.environment == 'preprod'
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          DRY_RUN: false
          CLUSTER: dev-gcp
          RESOURCE: .nais/config.yaml
          VARS: .nais/preprod-config.json
          VAR: image=${{ needs.build-and-push.outputs.image }}

  deploy-prod:
    name: Deploy to prod
    if: github.event.inputs.environment == 'prod'
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          DRY_RUN: false
          CLUSTER: prod-gcp
          RESOURCE: .nais/config.yaml
          VARS: .nais/prod-config.json
          VAR: image=${{ needs.build-and-push.outputs.image }}
