name: Build and deploy
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  CI: "true"

jobs:
  build-and-push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: skjemadigitalisering
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: prod
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/prod-config.json
          VAR: image=${{ needs.build-and-push.outputs.image }}

  smoke-test-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Smoke test the deployed app
        env:
          CYPRESS_BASE_URL: https://www.nav.no/soknader
        run: npm run cypress:ci
